name: Lint and Format Check

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check formatting with Biome
        run: npx biome format . --check
        
      - name: Run Biome lint
        run: npm run lint
        
      - name: Check import sorting
        run: npx eslint . --max-warnings 0
        
      - name: Run comprehensive check (format + lint + imports)
        run: npm run check
        
      - name: Type check
        run: npx tsc --noEmit